export const excursions = [
    {
        id: 1,
        name: "Остров 'Сулу ада' (Мальдивы Адрасан)",
        nameKey: "excursion1",
        descriptionKey: "excursion1_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion1_1.webp",
            "/images/excursions/excursion1_2.webp",
            "/images/excursions/excursion1_3.webp",
            "/images/excursions/excursion1_4.webp",
            "/images/excursions/excursion1_5.webp",
        ],
        price: 25,
        oldprice: 35,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 2,
        name: "Пикник рыбалка ULUPINAR",
        nameKey: "excursion2",
        descriptionKey: "excursion2_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion2_1.webp",
            "/images/excursions/excursion2_2.webp",
            "/images/excursions/excursion2_3.webp",
            "/images/excursions/excursion2_4.webp",
            "/images/excursions/excursion2_5.webp",
            "/images/excursions/excursion2_6.webp",
            "/images/excursions/excursion2_7.webp",
            "/images/excursions/excursion2_8.webp",
            "/images/excursions/excursion2_9.webp",
            "/images/excursions/excursion2_10.webp",
            "/images/excursions/excursion2_11.webp",
            "/images/excursions/excursion2_12.webp",
            "/images/excursions/excursion2_13.webp",
            "/images/excursions/excursion2_14.webp",
            "/images/excursions/excursion2_15.webp",
        ],
        price: 30,
        oldprice: 35,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },

    {
        id: 3,
        name: "Турецкие Мальдивы сулу ада на закате",
        nameKey: "excursion3",
        descriptionKey: "excursion3_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion3_1.webp",
            "/images/excursions/excursion3_2.webp",
            "/images/excursions/excursion3_3.webp",
            "/images/excursions/excursion3_4.webp",
            "/images/excursions/excursion3_5.webp",
            "/images/excursions/excursion3_6.webp",
            "/images/excursions/excursion3_7.webp",
            "/images/excursions/excursion3_8.webp",
            "/images/excursions/excursion3_9.webp",
            "/images/excursions/excursion3_10.webp",
        ],
        price: 30,
        oldprice: 35,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 4,
        name: "Путeшествие по голубым бухтам",
        nameKey: "excursion4",
        descriptionKey: "excursion4_desc",
        label: "НОВИНКА !!!",
        labelKey: "new",
        images: [
            "/images/excursions/excursion4_1.webp",
            "/images/excursions/excursion4_2.webp",
        ],
        price: 30,
        oldprice: 35,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 5,
        name: "Кападокия 2 дня",
        nameKey: "excursion5",
        descriptionKey: "excursion5_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion5_1.webp",
            "/images/excursions/excursion5_2.webp",
            "/images/excursions/excursion5_3.webp",
            "/images/excursions/excursion5_4.webp",
            "/images/excursions/excursion5_5.webp",
        ],
        price: 85,
        oldprice: 120,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },

    {
        id: 6,
        name: 'Яхта "La Melita" 28m',
        nameKey: "excursion6",
        descriptionKey: "excursion6_desc",
        label: "Уточняйте стоимость по телефону",
        labelKey: "take_price",
        images: [
            "/images/excursions/excursion6_1.webp",
            "/images/excursions/excursion6_2.webp",
        ],
        price: "500",
        oldprice: "",
        category: [
            "rent_yacht",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 7,
        name: "BMW 218 (автомат)",
        nameKey: "excursion7",
        descriptionKey: "excursion7_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion7_1.webp",
            "/images/excursions/excursion7_2.webp",
        ],
        price: 300,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 8,
        name: "Рыбалка в Анталии TROLLING & JEEGİNG",
        nameKey: "excursion8",
        descriptionKey: "excursion8_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion8_1.webp",
            "/images/excursions/excursion8_2.webp",
        ],
        price: 1200,
        oldprice: 1250,
        category: ["vip"],
    },
    {
        id: 9,
        name: "Экскурсия в Каш + пляж Капуташ",
        nameKey: "excursion9",
        descriptionKey: "excursion9_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion9_1.webp",
            "/images/excursions/excursion9_2.webp",
        ],
        price: 50,
        oldprice: 60,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "popular",
            "individual",
            "vip",
        ],
        category: [
            "rent_yacht",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 10,
        name: "Стамбул на 1 день (авиаперелёт)",
        nameKey: "excursion10",
        descriptionKey: "excursion10_desc",
        label: "Скиидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion10_1.webp",
            "/images/excursions/excursion10_2.webp",
            "/images/excursions/excursion10_3.webp",
            "/images/excursions/excursion10_4.webp",
            "/images/excursions/excursion10_5.webp",
            "/images/excursions/excursion10_6.webp",
            "/images/excursions/excursion10_7.webp",
            "/images/excursions/excursion10_8.webp",
            "/images/excursions/excursion10_9.webp",
            "/images/excursions/excursion10_10.webp",
            "/images/excursions/excursion10_11.webp",
            "/images/excursions/excursion10_12.webp",
            "/images/excursions/excursion10_13.webp",
            "/images/excursions/excursion10_14.webp",
            "/images/excursions/excursion10_15.webp",
            "/images/excursions/excursion10_16.webp",
            "/images/excursions/excursion10_17.webp",
            "/images/excursions/excursion10_18.webp",
            "/images/excursions/excursion10_19.webp",
            "/images/excursions/excursion10_20.webp",
            "/images/excursions/excursion10_21.webp",
            "/images/excursions/excursion10_22.webp",
            "/images/excursions/excursion10_23.webp",
            "/images/excursions/excursion10_24.webp",
        ],
        price: 285,
        oldprice: 295,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 11,
        name: "Трансфер Аэропорт Анталия Кемер",
        nameKey: "excursion11",
        descriptionKey: "excursion11_desc",
        label: "Заказ трансфера",
        labelKey: "order_transfer",
        images: [
            "/images/excursions/excursion11_1.webp",
            "/images/excursions/excursion11_2.webp",
            "/images/excursions/excursion11_3.webp",
            "/images/excursions/excursion11_4.webp",
            "/images/excursions/excursion11_5.webp",
            "/images/excursions/excursion11_6.webp",
            "/images/excursions/excursion11_7.webp",
            "/images/excursions/excursion11_8.webp",
            "/images/excursions/excursion11_9.webp",
        ],
        price: 0,
        oldprice: 0,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "transfers",
            "vip",
        ],
    },
    {
        id: 12,
        name: "Путешествие на корабле пиратском корабле",
        nameKey: "excursion12",
        descriptionKey: "excursion12_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion12_1.webp",
            "/images/excursions/excursion12_2.webp",
        ],
        price: 15,
        oldprice: 20,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 13,
        name: "Яхта 'Assol'",
        nameKey: "excursion13",
        descriptionKey: "excursion13_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion13_1.webp",
            "/images/excursions/excursion13_2.webp",
            "/images/excursions/excursion13_3.webp",
            "/images/excursions/excursion13_4.webp",
        ],
        price: 550,
        oldprice: 650,
        category: [
            "rent_yacht",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "vip",
        ],
    },
    {
        id: 14,
        name: "Анталия (старый город) + Водопады + ТЦ",
        nameKey: "excursion14",
        descriptionKey: "excursion14_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion14_1.webp",
            "/images/excursions/excursion14_2.webp",
            "/images/excursions/excursion14_3.webp",
            "/images/excursions/excursion14_4.webp",
            "/images/excursions/excursion14_5.webp",
        ],
        price: 30,
        oldprice: 45,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 15,
        name: "Volkswagen Jetta (бензин Автомат)",
        nameKey: "excursion15",
        descriptionKey: "excursion15_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion15_1.webp",
            "/images/excursions/excursion15_2.webp",
        ],
        price: 50,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 16,
        name: "Лимира - Демре - Кекова",
        nameKey: "excursion16",
        descriptionKey: "excursion16_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion16_1.webp",
            "/images/excursions/excursion16_2.webp",
            "/images/excursions/excursion16_3.webp",
            "/images/excursions/excursion16_4.webp",
            "/images/excursions/excursion16_5.webp",
        ],
        price: 30,
        oldprice: 35,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 17,
        name: "Лимира - Демре - Кекова",
        nameKey: "excursion17",
        descriptionKey: "excursion17_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion17_1.webp",
            "/images/excursions/excursion17_2.webp",
            "/images/excursions/excursion17_3.webp",
            "/images/excursions/excursion17_4.webp",
            "/images/excursions/excursion17_5.webp",
        ],
        price: 45,
        oldprice: 50,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 18,
        name: "Памуккале",
        nameKey: "excursion18",
        descriptionKey: "excursion18_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion18_1.webp",
            "/images/excursions/excursion18_2.webp",
            "/images/excursions/excursion18_3.webp",
            "/images/excursions/excursion18_4.webp",
            "/images/excursions/excursion18_5.webp",
            "/images/excursions/excursion18_6.webp",
            "/images/excursions/excursion18_7.webp",
            "/images/excursions/excursion18_8.webp",
            "/images/excursions/excursion18_9.webp",
            "/images/excursions/excursion18_10.webp",
            "/images/excursions/excursion18_11.webp",
            "/images/excursions/excursion18_12.webp",
            "/images/excursions/excursion18_13.webp",
            "/images/excursions/excursion18_14.webp",
            "/images/excursions/excursion18_15.webp",
            "/images/excursions/excursion18_16.webp",
        ],
        price: 60,
        oldprice: 65,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 19,
        name: "Памуккале + озеро Салда",
        nameKey: "excursion19",
        descriptionKey: "excursion19_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion19_1.webp",
            "/images/excursions/excursion19_2.webp",
            "/images/excursions/excursion19_3.webp",
            "/images/excursions/excursion19_4.webp",
            "/images/excursions/excursion19_5.webp",
        ],
        price: 65,
        oldprice: 70,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 20,
        name: "Памуккале + Воздушный шар",
        nameKey: "excursion20",
        descriptionKey: "excursion20_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion20_1.webp",
            "/images/excursions/excursion20_2.webp",
            "/images/excursions/excursion20_3.webp",
            "/images/excursions/excursion20_4.webp",
            "/images/excursions/excursion20_5.webp",
        ],
        price: 150,
        oldprice: 160,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "vip",
        ],
    },
    {
        id: 21,
        name: "Памуккале наследие юнеско",
        nameKey: "excursion21",
        descriptionKey: "excursion21_desc",
        label: "Индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion21_1.webp",
            "/images/excursions/excursion21_2.webp",
            "/images/excursions/excursion21_3.webp",
            "/images/excursions/excursion21_4.webp",
            "/images/excursions/excursion21_5.webp",
        ],
        price: 300,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "individual",
            "vip",
        ],
    },
    {
        id: 22,
        name: "Пляж Капуташ посещение г. Каш",
        nameKey: "excursion22",
        descriptionKey: "excursion22_desc",
        label: "Индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion22_1.webp",
            "/images/excursions/excursion22_2.webp",
            "/images/excursions/excursion22_3.webp",
            "/images/excursions/excursion22_4.webp",
            "/images/excursions/excursion22_5.webp",
        ],
        price: 300,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "individual",
            "vip",
        ],
    },
    {
        id: 23,
        name: "Fiat Egea 2021 год (бензин механика)",
        nameKey: "excursion23",
        descriptionKey: "excursion23_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion23_1.webp",
            "/images/excursions/excursion23_2.webp",
            "/images/excursions/excursion23_3.webp",
            "/images/excursions/excursion23_4.webp",
            "/images/excursions/excursion23_5.webp",
        ],
        price: 45,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 24,
        name: "Dacia Lodgy 2021г механика на 7 человек",
        nameKey: "excursion24",
        descriptionKey: "excursion24_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion24_1.webp",
            "/images/excursions/excursion24_2.webp",
            "/images/excursions/excursion24_3.webp",
            "/images/excursions/excursion24_4.webp",
            "/images/excursions/excursion24_5.webp",
        ],
        price: 45,
        oldprice: "",
        category: ["rent_auto"],
    },

    {
        id: 25,
        name: "Обзорная экскурсия по Анталии",
        nameKey: "excursion25",
        descriptionKey: "excursion25_desc",
        label: "Индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion25_1.webp",
            "/images/excursions/excursion25_2.webp",
            "/images/excursions/excursion25_3.webp",
            "/images/excursions/excursion25_4.webp",
            "/images/excursions/excursion25_5.webp",
        ],
        price: 150,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "individual",
            "vip",
        ],
    },
    {
        id: 26,
        name: "Канатная дорога Тахталы 2365м",
        nameKey: "excursion26",
        descriptionKey: "excursion26_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion26_1.webp",
            "/images/excursions/excursion26_2.webp",
            "/images/excursions/excursion26_3.webp",
            "/images/excursions/excursion26_4.webp",
            "/images/excursions/excursion26_5.webp",
            "/images/excursions/excursion26_6.webp",
            "/images/excursions/excursion26_7.webp",
            "/images/excursions/excursion26_8.webp",
            "/images/excursions/excursion26_9.webp",
            "/images/excursions/excursion26_10.webp",
            "/images/excursions/excursion26_11.webp",
            "/images/excursions/excursion26_12.webp",
            "/images/excursions/excursion26_13.webp",
            "/images/excursions/excursion26_14.webp",
            "/images/excursions/excursion26_15.webp",
        ],
        price: 55,
        oldprice: 60,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 27,
        name: "Тахталы 2365м (закат)",
        nameKey: "excursion27",
        descriptionKey: "excursion27_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion27_1.webp",
            "/images/excursions/excursion27_2.webp",
            "/images/excursions/excursion27_3.webp",
            "/images/excursions/excursion27_4.webp",
            "/images/excursions/excursion27_5.webp",
        ],
        price: 80,
        oldprice: 85,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 28,
        name: "Джип сафари",
        nameKey: "excursion28",
        descriptionKey: "excursion28_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion28_1.webp",
            "/images/excursions/excursion28_2.webp",
            "/images/excursions/excursion28_3.webp",
            "/images/excursions/excursion28_4.webp",
            "/images/excursions/excursion28_5.webp",
        ],
        price: 30,
        oldprice: 35,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 29,
        name: "Огни Химеры + Олимпос + Улупынар",
        nameKey: "excursion29",
        descriptionKey: "excursion29_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion29_1.webp",
            "/images/excursions/excursion29_2.webp",
            "/images/excursions/excursion29_3.webp",
            "/images/excursions/excursion29_4.webp",
            "/images/excursions/excursion29_5.webp",
        ],
        price: 30,
        oldprice: 35,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 30,
        name: "Каньон Гёйнюк",
        name_en: "Gainyuk Canyon",
        nameKey: "excursion30",
        descriptionKey: "excursion30_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion30_1.webp",
            "/images/excursions/excursion30_2.webp",
            "/images/excursions/excursion30_3.webp",
            "/images/excursions/excursion30_4.webp",
            "/images/excursions/excursion30_5.webp",
        ],
        price: 20,
        oldprice: 25,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
        ],
    },

    {
        id: 31,
        name: "Дайвинг",
        nameKey: "excursion31",
        descriptionKey: "excursion31_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion31_1.webp",
            "/images/excursions/excursion31_2.webp",
            "/images/excursions/excursion31_3.webp",
            "/images/excursions/excursion31_4.webp",
            "/images/excursions/excursion31_5.webp",
        ],
        price: 25,
        oldprice: 30,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
        ],
    },
    {
        id: 32,
        name: "Аренда виллы 5+1 Кемер / Анталья",
        nameKey: "excursion32",
        descriptionKey: "excursion32_desc",
        label: "Кемер",
        labelKey: "kemer",
        images: [
            "/images/excursions/excursion32_1.webp",
            "/images/excursions/excursion32_2.webp",
            "/images/excursions/excursion32_3.webp",
            "/images/excursions/excursion32_4.webp",
            "/images/excursions/excursion32_5.webp",
        ],
        price: 8000,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 33,
        name: "Аренда виллы в Кемере (3+1 200мк)",
        nameKey: "excursion33",
        descriptionKey: "excursion33_desc",
        label: "Кемер",
        labelKey: "kemer",
        images: [
            "/images/excursions/excursion33_1.webp",
            "/images/excursions/excursion33_2.webp",
            "/images/excursions/excursion33_3.webp",
            "/images/excursions/excursion33_4.webp",
            "/images/excursions/excursion33_5.webp",
        ],
        price: 6000,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 34,
        name: "Аренда квартиры в Кемере 2+1 (200м до моря)",
        nameKey: "excursion34",
        descriptionKey: "excursion34_desc",
        label: "Кемер",
        labelKey: "kemer",
        images: [
            "/images/excursions/excursion34_1.webp",
            "/images/excursions/excursion34_2.webp",
            "/images/excursions/excursion34_3.webp",
            "/images/excursions/excursion34_4.webp",
            "/images/excursions/excursion34_5.webp",
        ],
        price: 1500,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 35,
        name: "Аренда квартиры в Кемере",
        nameKey: "excursion35",
        descriptionKey: "excursion35_desc",
        label: "Цену уточняйте по телефону",
        labelKey: "take_price",
        images: [
            "/images/excursions/excursion35_1.webp",
            "/images/excursions/excursion35_2.webp",
            "/images/excursions/excursion35_3.webp",
            "/images/excursions/excursion35_4.webp",
            "/images/excursions/excursion35_5.webp",
        ],
        price: 0,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 36,
        name: "Аренда виллы в Кемере",
        nameKey: "excursion36",
        descriptionKey: "excursion36_desc",
        label: "Цену уточняйте по телефону",
        labelKey: "take_price",
        images: [
            "/images/excursions/excursion36_1.webp",
            "/images/excursions/excursion36_2.webp",
            "/images/excursions/excursion36_3.webp",
            "/images/excursions/excursion36_4.webp",
            "/images/excursions/excursion36_5.webp",
        ],
        price: 0,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 37,
        name: "Аренда виллы в Бодруме. Вилла 1",
        nameKey: "excursion6",
        descriptionKey: "excursion37_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion37_1.webp",
            "/images/excursions/excursion37_2.webp",
            "/images/excursions/excursion37_3.webp",
            "/images/excursions/excursion37_4.webp",
            "/images/excursions/excursion37_5.webp",
        ],
        price: 235,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 38,
        name: "Аренда виллы в Бодруме. Вилла 2",
        nameKey: "excursion38",
        descriptionKey: "excursion38_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion38_1.webp",
            "/images/excursions/excursion38_2.webp",
            "/images/excursions/excursion38_3.webp",
            "/images/excursions/excursion38_4.webp",
            "/images/excursions/excursion38_5.webp",
        ],
        price: 230,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 39,
        name: "Аренда виллы в Бодруме. Вилла 3",
        nameKey: "excursion39",
        descriptionKey: "excursion39_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion39_1.webp",
            "/images/excursions/excursion39_2.webp",
            "/images/excursions/excursion39_3.webp",
            "/images/excursions/excursion39_4.webp",
            "/images/excursions/excursion39_5.webp",
        ],
        price: 360,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 40,
        name: "Аренда виллы в Бодруме. Вилла 4",
        nameKey: "excursion40",
        descriptionKey: "excursion40_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion40_1.webp",
            "/images/excursions/excursion40_2.webp",
            "/images/excursions/excursion40_3.webp",
            "/images/excursions/excursion40_4.webp",
            "/images/excursions/excursion40_5.webp",
        ],
        price: 890,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 41,
        name: "Аренда виллы в Бодруме. Вилла 5",
        nameKey: "excursion41",
        descriptionKey: "excursion41_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion41_1.webp",
            "/images/excursions/excursion41_2.webp",
            "/images/excursions/excursion41_3.webp",
            "/images/excursions/excursion41_4.webp",
            "/images/excursions/excursion41_5.webp",
        ],
        price: 360,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 42,
        name: "Аренда виллы в Бодруме. Вилла 6",
        nameKey: "excursion42",
        descriptionKey: "excursion42_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion42_1.webp",
            "/images/excursions/excursion42_2.webp",
            "/images/excursions/excursion42_3.webp",
            "/images/excursions/excursion42_4.webp",
            "/images/excursions/excursion42_5.webp",
        ],
        price: 370,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 43,
        name: "Аренда виллы в Бодруме. Вилла 7",
        nameKey: "excursion43",
        descriptionKey: "excursion43_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion43_1.webp",
            "/images/excursions/excursion43_2.webp",
            "/images/excursions/excursion43_3.webp",
            "/images/excursions/excursion43_4.webp",
            "/images/excursions/excursion43_5.webp",
        ],
        price: 360,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 44,
        name: "Аренда виллы в Бодруме. Вилла 8",
        nameKey: "excursion44",
        descriptionKey: "excursion44_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion44_1.webp",
            "/images/excursions/excursion44_2.webp",
            "/images/excursions/excursion44_3.webp",
            "/images/excursions/excursion44_4.webp",
            "/images/excursions/excursion44_5.webp",
        ],
        price: 550,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 45,
        name: "Аренда виллы в Бодруме. Вилла 9",
        nameKey: "excursion45",
        descriptionKey: "excursion45_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion45_1.webp",
            "/images/excursions/excursion45_2.webp",
            "/images/excursions/excursion45_3.webp",
            "/images/excursions/excursion45_4.webp",
            "/images/excursions/excursion45_5.webp",
        ],
        price: 210,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 46,
        name: "Аренда виллы в Бодруме. Вилла 10",
        nameKey: "excursion46",
        descriptionKey: "excursion46_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion46_1.webp",
            "/images/excursions/excursion46_2.webp",
            "/images/excursions/excursion46_3.webp",
            "/images/excursions/excursion46_4.webp",
            "/images/excursions/excursion46_5.webp",
        ],
        price: 220,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 47,
        name: "Аренда виллы в Бодруме. Вилла 11",
        nameKey: "excursion47",
        descriptionKey: "excursion47_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion47_1.webp",
            "/images/excursions/excursion47_2.webp",
            "/images/excursions/excursion47_3.webp",
            "/images/excursions/excursion47_4.webp",
            "/images/excursions/excursion47_5.webp",
        ],
        price: 240,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 48,
        name: "Аренда виллы в Бодруме. Вилла 12",
        nameKey: "excursion48",
        descriptionKey: "excursion48_desc",
        label: "Сутки",
        labelKey: "daily",
        images: [
            "/images/excursions/excursion48_1.webp",
            "/images/excursions/excursion48_2.webp",
            "/images/excursions/excursion48_3.webp",
            "/images/excursions/excursion48_4.webp",
            "/images/excursions/excursion48_5.webp",
        ],
        price: 270,
        oldprice: "",
        category: ["rent_villa"],
    },
    {
        id: 49,
        name: "Mall of Antalya (из Кемера)",
        nameKey: "excursion49",
        descriptionKey: "excursion49_desc",
        label: "Трансфер",
        labelKey: "transfer",
        images: [
            "/images/excursions/excursion49_1.webp",
            "/images/excursions/excursion49_2.webp",
            "/images/excursions/excursion49_3.webp",
            "/images/excursions/excursion49_4.webp",
            "/images/excursions/excursion49_5.webp",
        ],
        price: 80,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
            "vip",
        ],
    },
    {
        id: 50,
        name: "Terra city (из Кемера)",
        nameKey: "excursion50",
        descriptionKey: "excursion50_desc",
        label: "Трансфер",
        labelKey: "transfer",
        images: [
            "/images/excursions/excursion50_1.webp",
            "/images/excursions/excursion50_2.webp",
            "/images/excursions/excursion50_3.webp",
            "/images/excursions/excursion50_4.webp",
            "/images/excursions/excursion50_5.webp",
        ],
        price: 90,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
            "vip",
        ],
    },
    {
        id: 51,
        name: "Özdilek Park (из Кемера)",
        nameKey: "excursion51",
        descriptionKey: "excursion51_desc",
        label: "Трансфер",
        labelKey: "transfer",
        images: [
            "/images/excursions/excursion51_1.webp",
            "/images/excursions/excursion51_2.webp",
            "/images/excursions/excursion51_3.webp",
            "/images/excursions/excursion51_4.webp",
            "/images/excursions/excursion51_5.webp",
        ],
        price: 80,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
        ],
    },
    {
        id: 52,
        name: "Mark Antalya (из Кемера)",
        nameKey: "excursion52",
        descriptionKey: "excursion52_desc",
        label: "Трансфер",
        labelKey: "transfer",
        images: [
            "/images/excursions/excursion52_1.webp",
            "/images/excursions/excursion52_2.webp",
            "/images/excursions/excursion52_3.webp",
            "/images/excursions/excursion52_4.webp",
            "/images/excursions/excursion52_5.webp",
        ],
        price: 80,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
        ],
    },
    {
        id: 53,
        name: "Migros 5M Antalya (из Кемера)",
        nameKey: "excursion53",
        descriptionKey: "excursion53_desc",
        label: "Трансфер",
        labelKey: "transfer",
        images: [
            "/images/excursions/excursion53_1.webp",
            "/images/excursions/excursion53_2.webp",
            "/images/excursions/excursion53_3.webp",
            "/images/excursions/excursion53_4.webp",
            "/images/excursions/excursion53_5.webp",
        ],
        price: 80,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
        ],
    },
    {
        id: 54,
        name: "Фабрика кожи и мехов",
        nameKey: "excursion54",
        descriptionKey: "excursion54_desc",
        label: "Скидки",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion54_1.webp",
            "/images/excursions/excursion54_2.webp",
            "/images/excursions/excursion54_3.webp",
            "/images/excursions/excursion54_4.webp",
            "/images/excursions/excursion54_5.webp",
        ],
        price: 0,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
            "vip",
        ],
    },
    {
        id: 55,
        name: "Кожа меха и дубленки",
        nameKey: "excursion55",
        descriptionKey: "excursion55_desc",
        label: "Скидки",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion55_1.webp",
            "/images/excursions/excursion55_2.webp",
            "/images/excursions/excursion55_3.webp",
            "/images/excursions/excursion55_4.webp",
            "/images/excursions/excursion55_5.webp",
        ],
        price: 0,
        oldprice: "",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "shopping",
            "vip",
        ],
    },
    {
        id: 56,
        name: "Mercedes benz CLA (Автомат)",
        nameKey: "excursion56",
        descriptionKey: "excursion56_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion56_1.webp",
            "/images/excursions/excursion56_2.webp",
            "/images/excursions/excursion56_3.webp",
            "/images/excursions/excursion56_4.webp",
            "/images/excursions/excursion56_5.webp",
        ],
        price: 150,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 57,
        name: "BMW 7.30D (автомат)",
        nameKey: "excursion57",
        descriptionKey: "excursion57_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion57_1.webp",
            "/images/excursions/excursion57_2.webp",
            "/images/excursions/excursion57_3.webp",
            "/images/excursions/excursion57_4.webp",
            "/images/excursions/excursion57_5.webp",
        ],
        price: 300,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 58,
        name: "RANGE ROVER SPORT (автомат)",
        nameKey: "excursion58",
        descriptionKey: "excursion58_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion58_1.webp",
            "/images/excursions/excursion58_2.webp",
            "/images/excursions/excursion58_3.webp",
            "/images/excursions/excursion58_4.webp",
            "/images/excursions/excursion58_5.webp",
        ],
        price: 300,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 59,
        name: "Mercedes vito 119 CDI (автомат)",
        nameKey: "excursion59",
        descriptionKey: "excursion59_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion59_1.webp",
            "/images/excursions/excursion59_2.webp",
            "/images/excursions/excursion59_3.webp",
            "/images/excursions/excursion59_4.webp",
            "/images/excursions/excursion59_5.webp",
            "/images/excursions/excursion59_6.webp",
            "/images/excursions/excursion59_7.webp",
        ],
        price: 300,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 60,
        name: "BMW 420 cabrio",
        nameKey: "excursion60",
        descriptionKey: "excursion60_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion60_1.webp",
            "/images/excursions/excursion60_2.webp",
            "/images/excursions/excursion60_3.webp",
            "/images/excursions/excursion60_4.webp",
            "/images/excursions/excursion60_5.webp",
        ],
        price: 300,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 61,
        name: "BMW 6 cabrio",
        nameKey: "excursion61",
        descriptionKey: "excursion61_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion61_1.webp",
            "/images/excursions/excursion61_2.webp",
            "/images/excursions/excursion61_3.webp",
            "/images/excursions/excursion61_4.webp",
            "/images/excursions/excursion61_5.webp",
        ],
        price: 300,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 62,
        name: "BMW 320 cabrio",
        nameKey: "excursion62",
        descriptionKey: "excursion62_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion62_1.webp",
            "/images/excursions/excursion62_2.webp",
            "/images/excursions/excursion62_3.webp",
            "/images/excursions/excursion62_4.webp",
            "/images/excursions/excursion62_5.webp",
        ],
        price: 250,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 63,
        name: "BMW 218 cabrio",
        nameKey: "excursion63",
        descriptionKey: "excursion63_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion63_1.webp",
            "/images/excursions/excursion63_2.webp",
            "/images/excursions/excursion63_3.webp",
            "/images/excursions/excursion63_4.webp",
            "/images/excursions/excursion63_5.webp",
        ],
        price: 200,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 64,
        name: "Яхта Tu navy 1",
        nameKey: "excursion64",
        descriptionKey: "excursion64_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion64_1.webp",
            "/images/excursions/excursion64_2.webp",
            "/images/excursions/excursion64_3.webp",
            "/images/excursions/excursion64_4.webp",
            "/images/excursions/excursion64_5.webp",
        ],
        price: 750,
        oldprice: "850",
        category: ["rent_yacht"],
    },
    {
        id: 65,
        name: "Мира-Кекова (Храм Николая Чудотворца)",
        name_en: "Mira Kekova (Church of St. Nicholas the Wonderworker)",
        nameKey: "excursion65",
        descriptionKey: "excursion65_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion65_1.webp",
            "/images/excursions/excursion65_2.webp",
            "/images/excursions/excursion65_3.webp",
            "/images/excursions/excursion65_4.webp",
            "/images/excursions/excursion65_5.webp",
            "/images/excursions/excursion65_6.webp",
            "/images/excursions/excursion65_7.webp",
            "/images/excursions/excursion65_8.webp",
            "/images/excursions/excursion65_9.webp",
            "/images/excursions/excursion65_10.webp",
            "/images/excursions/excursion65_11.webp",
            "/images/excursions/excursion65_12.webp",
            "/images/excursions/excursion65_13.webp",
            "/images/excursions/excursion65_14.webp",
            "/images/excursions/excursion65_15.webp",
        ],
        price: 200,
        oldprice: 210,
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 66,
        name: "Акваленд «The Land of Legends Park Belek»",
        name_en: "Aqualand «The Land of Legends Park Belek»",
        nameKey: "excursion66",
        descriptionKey: "excursion66_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion66_1.webp",
            "/images/excursions/excursion66_2.webp",
            "/images/excursions/excursion66_3.webp",
            "/images/excursions/excursion66_4.webp",
            "/images/excursions/excursion66_5.webp",
            "/images/excursions/excursion66_6.webp",
            "/images/excursions/excursion66_7.webp",
            "/images/excursions/excursion66_8.webp",
            "/images/excursions/excursion66_9.webp",
            "/images/excursions/excursion66_10.webp",
            "/images/excursions/excursion66_11.webp",
            "/images/excursions/excursion66_12.webp",
            "/images/excursions/excursion66_13.webp",
            "/images/excursions/excursion66_14.webp",
        ],
        price: 100,
        oldprice: 105,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 67,
        name: "Яхта 'Briz' Бриз",
        nameKey: "excursion67",
        descriptionKey: "excursion67_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion67_1.webp",
            "/images/excursions/excursion67_2.webp",
            "/images/excursions/excursion67_3.webp",
            "/images/excursions/excursion67_4.webp",
            "/images/excursions/excursion67_5.webp",
        ],
        price: 450,
        oldprice: "500",
        category: ["rent_yacht"],
    },
    {
        id: 68,
        name: "Яхта 'Aras'",
        nameKey: "excursion68",
        descriptionKey: "excursion68_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion68_1.webp",
            "/images/excursions/excursion68_2.webp",
            "/images/excursions/excursion68_3.webp",
            "/images/excursions/excursion68_4.webp",
            "/images/excursions/excursion68_5.webp",
        ],
        price: 400,
        oldprice: "450",
        category: ["rent_yacht"],
    },
    {
        id: 69,
        name: "Яхта 'Mavim'",
        nameKey: "excursion69",
        descriptionKey: "excursion69_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion69_1.webp",
            "/images/excursions/excursion69_2.webp",
            "/images/excursions/excursion69_3.webp",
            "/images/excursions/excursion69_4.webp",
            "/images/excursions/excursion69_5.webp",
        ],
        price: 450,
        oldprice: "500",
        category: ["rent_yacht"],
    },
    {
        id: 70,
        name: "Турецкие Мальдивы - озеро Салда",
        name_en: "Turkish Maldives - Lake Salda",
        nameKey: "excursion70",
        descriptionKey: "excursion70_desc",
        label: "индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion70_1.webp",
            "/images/excursions/excursion70_2.webp",
            "/images/excursions/excursion70_3.webp",
            "/images/excursions/excursion70_4.webp",
            "/images/excursions/excursion70_5.webp",
        ],
        price: 200,
        oldprice: 210,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 71,
        name: "Яхта 'Jet süha'",
        nameKey: "excursion71",
        descriptionKey: "excursion71_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion71_1.webp",
            "/images/excursions/excursion71_2.webp",
            "/images/excursions/excursion71_3.webp",
            "/images/excursions/excursion71_4.webp",
            "/images/excursions/excursion71_5.webp",
        ],
        price: 450,
        oldprice: "500",
        category: ["rent_yacht"],
    },
    {
        id: 72,
        name: "Яхта «Beys 07»",
        nameKey: "excursion72",
        descriptionKey: "excursion72_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion72_1.webp",
            "/images/excursions/excursion72_2.webp",
            "/images/excursions/excursion72_3.webp",
            "/images/excursions/excursion72_4.webp",
            "/images/excursions/excursion72_5.webp",
        ],
        price: 650,
        oldprice: "700",
        category: ["rent_yacht"],
    },
    {
        id: 73,
        name: "Яхта '19'",
        nameKey: "excursion73",
        descriptionKey: "excursion73_desc",
        label: "скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion73_1.webp",
            "/images/excursions/excursion73_2.webp",
            "/images/excursions/excursion73_3.webp",
            "/images/excursions/excursion73_4.webp",
            "/images/excursions/excursion73_5.webp",
        ],
        price: 800,
        oldprice: "900",
        category: ["rent_yacht"],
    },
    {
        id: 74,
        name: "Рафтинг (14км сплав)",
        name_en: "Rafting (14km rafting)",
        nameKey: "excursion74",
        descriptionKey: "excursion74_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion74_1.webp",
            "/images/excursions/excursion74_2.webp",
            "/images/excursions/excursion74_3.webp",
            "/images/excursions/excursion74_4.webp",
            "/images/excursions/excursion74_5.webp",
            "/images/excursions/excursion74_6.webp",
            "/images/excursions/excursion74_7.webp",
            "/images/excursions/excursion74_8.webp",
            "/images/excursions/excursion74_9.webp",
            "/images/excursions/excursion74_10.webp",
            "/images/excursions/excursion74_11.webp",
            "/images/excursions/excursion74_12.webp",
            "/images/excursions/excursion74_13.webp",
            "/images/excursions/excursion74_14.webp",
            "/images/excursions/excursion74_15.webp",
        ],
        price: 20,
        oldprice: 25,
        category: ["excursion", "from_kemer"],
    },
    {
        id: 75,
        name: "Прогулка на лошадях в «Berke Rancho»",
        name_en: "Horse riding at the Berke Rancho",
        nameKey: "excursion75",
        descriptionKey: "excursion75_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion75_1.webp",
            "/images/excursions/excursion75_2.webp",
            "/images/excursions/excursion75_3.webp",
            "/images/excursions/excursion75_4.webp",
            "/images/excursions/excursion75_5.webp",
        ],
        price: 35,
        oldprice: 40,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 76,
        name: "Аквариум в Анталии",
        name_en: "Aquarium Antalya",
        nameKey: "excursion76",
        descriptionKey: "excursion76_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion76_1.webp",
            "/images/excursions/excursion76_2.webp",
            "/images/excursions/excursion76_3.webp",
            "/images/excursions/excursion76_4.webp",
            "/images/excursions/excursion76_5.webp",
        ],
        price: 55,
        oldprice: 60,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 77,
        name: "Динопарк в Гёйнюке",
        name_en: "Dinopark in Goyniuk",
        nameKey: "excursion77",
        descriptionKey: "excursion77_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion77_1.webp",
            "/images/excursions/excursion77_2.webp",
            "/images/excursions/excursion77_3.webp",
            "/images/excursions/excursion77_4.webp",
            "/images/excursions/excursion77_5.webp",
        ],
        price: 30,
        oldprice: "35",
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 78,
        name: "Шоу дельфинов в Анталии",
        name_en: "Dolphin Show in Antalya",
        nameKey: "excursion78",
        descriptionKey: "excursion78_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion78_1.webp",
            "/images/excursions/excursion78_2.webp",
            "/images/excursions/excursion78_3.webp",
            "/images/excursions/excursion78_4.webp",
            "/images/excursions/excursion78_5.webp",
        ],
        price: 33,
        oldprice: 45,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 79,
        name: "Плавание с дельфинами",
        name_en: "Swimming with dolphins",
        nameKey: "excursion79",
        descriptionKey: "excursion79_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion79_1.webp",
            "/images/excursions/excursion79_2.webp",
            "/images/excursions/excursion79_3.webp",
            "/images/excursions/excursion79_4.webp",
            "/images/excursions/excursion79_5.webp",
        ],
        price: 100,
        oldprice: 105,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 80,
        name: "Огни Анатолии «Fire of Anatolia»",
        name_en: "Lights of Anatolia «Fire of Anatolia»",
        nameKey: "excursion80",
        descriptionKey: "excursion80_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion80_1.webp",
            "/images/excursions/excursion80_2.webp",
            "/images/excursions/excursion80_3.webp",
            "/images/excursions/excursion80_4.webp",
            "/images/excursions/excursion80_5.webp",
        ],
        price: 65,
        oldprice: 70,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 81,
        name: "Параглайдинг 1000m",
        name_en: "Paragliding 1000m",
        nameKey: "excursion81",
        descriptionKey: "excursion81_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion81_1.webp",
            "/images/excursions/excursion81_2.webp",
            "/images/excursions/excursion81_3.webp",
            "/images/excursions/excursion81_4.webp",
            "/images/excursions/excursion81_5.webp",
        ],
        price: 150,
        oldprice: 165,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 82,
        name: "Параглайдинг с Тахталы 2365m",
        name_en: "Paragliding from Takhtala 2365m",
        nameKey: "excursion82",
        descriptionKey: "excursion82_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion82_1.webp",
            "/images/excursions/excursion82_2.webp",
            "/images/excursions/excursion82_3.webp",
            "/images/excursions/excursion82_4.webp",
            "/images/excursions/excursion82_5.webp",
        ],
        price: 285,
        oldprice: 295,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 83,
        name: "Историко-археологический музей Анталии",
        name_en: "Historical and Archaeological Museum of Antalya",
        nameKey: "excursion83",
        descriptionKey: "excursion83_desc",
        label: "индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion83_1.webp",
            "/images/excursions/excursion83_2.webp",
            "/images/excursions/excursion83_3.webp",
            "/images/excursions/excursion83_4.webp",
            "/images/excursions/excursion83_5.webp",
        ],
        price: 100,
        oldprice: 110,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 84,
        name: "Сагалассос - город античных фонтанов",
        name_en: "Sagalassos is a city of ancient fountains",
        nameKey: "excursion84",
        descriptionKey: "excursion84_desc",
        label: "индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion84_1.webp",
            "/images/excursions/excursion84_2.webp",
            "/images/excursions/excursion84_3.webp",
            "/images/excursions/excursion84_4.webp",
            "/images/excursions/excursion84_5.webp",
        ],
        price: 200,
        oldprice: 205,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 85,
        name: "Лавандовые поля в Турции (сезонно)",
        name_en: "Lavender fields in Turkey (seasonal)",
        nameKey: "excursion85",
        descriptionKey: "excursion85_desc",
        label: "индивидуально",
        labelKey: "personal",
        images: [
            "/images/excursions/excursion85_1.webp",
            "/images/excursions/excursion85_2.webp",
            "/images/excursions/excursion85_3.webp",
            "/images/excursions/excursion85_4.webp",
            "/images/excursions/excursion85_5.webp",
        ],
        price: 200,
        oldprice: 210,
        category: [
            "excursion",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 86,
        name: "Kia Rio (автомат)",
        name_en: "Kia Rio (automatic)",
        nameKey: "excursion86",
        descriptionKey: "excursion86_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion86_1.webp",
            "/images/excursions/excursion86_2.webp",
            "/images/excursions/excursion86_3.webp",
            "/images/excursions/excursion86_4.webp",
            "/images/excursions/excursion86_5.webp",
        ],
        price: 50,
        oldprice: "",
        category: ["rent_auto"],
    },
    {
        id: 87,
        name: "Luxury Yacht Bodrum 36m",
        name_en: "Luxury Yacht Bodrum 36m",
        nameKey: "excursion87",
        descriptionKey: "excursion87_desc",
        label: "Уточняйте стоимость по телефону",
        labelKey: "take_price",
        images: [
            "/images/excursions/excursion87_1.webp",
            "/images/excursions/excursion87_2.webp",
            "/images/excursions/excursion87_3.webp",
            "/images/excursions/excursion87_4.webp",
            "/images/excursions/excursion87_5.webp",
            "/images/excursions/excursion87_6.webp",
            "/images/excursions/excursion87_7.webp",
            "/images/excursions/excursion87_8.webp",
            "/images/excursions/excursion87_9.webp",
            "/images/excursions/excursion87_10.webp",
            "/images/excursions/excursion87_11.webp",
            "/images/excursions/excursion87_12.webp",
            "/images/excursions/excursion87_13.webp",
            "/images/excursions/excursion87_14.webp",
            "/images/excursions/excursion87_15.webp",
            "/images/excursions/excursion87_16.webp",
            "/images/excursions/excursion87_17.webp",
            "/images/excursions/excursion87_18.webp",
            "/images/excursions/excursion87_19.webp",
        ],
        price: 7500,
        oldprice: "",
        category: [
            "rent_yacht",
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
            "vip",
        ],
    },
    {
        id: 88,
        name: 'Аквапарк "Долу Су"',
        name_en: 'Water Park "Dogusu"',
        nameKey: "excursion88",
        descriptionKey: "excursion88_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion88_1.webp",
            "/images/excursions/excursion88_2.webp",
            "/images/excursions/excursion88_3.webp",
            "/images/excursions/excursion88_4.webp",
            "/images/excursions/excursion88_5.webp",
            "/images/excursions/excursion88_6.webp",
            "/images/excursions/excursion88_7.webp",
        ],
        price: 30,
        oldprice: "35",
        category: [
            "from_kemer",
            "from_alania",
            "from_side",
            "from_antalia",
            "from_belek",
            "from_marmaris",
            "popular",
            "individual",
        ],
    },
    {
        id: 89,
        name: 'Мерседес "Майбах"',
        name_en: 'Water Park "Dogusu"',
        nameKey: "excursion89",
        descriptionKey: "excursion89_desc",
        label: "",
        labelKey: "",
        images: [
            "/images/excursions/excursion89_1.webp",
            "/images/excursions/excursion89_2.webp",
            "/images/excursions/excursion89_3.webp",
            "/images/excursions/excursion89_4.webp",
            "/images/excursions/excursion89_5.webp",
            "/images/excursions/excursion89_6.webp",
            "/images/excursions/excursion89_7.webp",
            "/images/excursions/excursion89_8.webp",
            "/images/excursions/excursion89_9.webp",
            "/images/excursions/excursion89_10.webp",
            "/images/excursions/excursion89_11.webp",
            "/images/excursions/excursion89_12.webp",
            "/images/excursions/excursion89_13.webp",
            "/images/excursions/excursion89_14.webp",
            "/images/excursions/excursion89_15.webp",
            "/images/excursions/excursion89_16.webp",
            "/images/excursions/excursion89_17.webp",
            "/images/excursions/excursion89_18.webp",
            "/images/excursions/excursion89_19.webp",
            "/images/excursions/excursion89_20.webp",
            "/images/excursions/excursion89_21.webp",
            "/images/excursions/excursion89_22.webp",
        ],
        price: 350,
        oldprice: "400",
        category: ["rent_auto", "popular", "individual"],
    },
];
