export const excursions = [
    {
        id: 1,
        name: "Остров 'Сулу ада' (Мальдивы Адрасан)",
        nameKey: "excursion1",
        descriptionKey: "excursion1_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion1_1.webp",
            "/images/excursions/excursion1_2.webp",
        ],
        price: 25,
        oldprice: 35,
        category: ["excursion", "from_kemer", "popular"],
    },
    {
        id: 2,
        name: "Турецкие Мальдивы сулу ада на рассвете",
        nameKey: "excursion2",
        descriptionKey: "excursion2_desc",
        label: "НОВИНКА !!!",
        labelKey: "new",
        images: [
            "/images/excursions/excursion2_1.webp",
            "/images/excursions/excursion2_2.webp",
        ],
        price: 35,
        oldprice: 40,
        category: ["excursion", "from_kemer", "popular"],
    },
    {
        id: 3,
        name: "Турецкие Мальдивы сулу ада на закате",
        nameKey: "excursion3",
        descriptionKey: "excursion3_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion3_1.webp",
            "/images/excursions/excursion3_2.webp",
        ],
        price: 30,
        oldprice: 35,
        category: ["excursion", "from_kemer", "popular"],
    },
    {
        id: 4,
        name: "Путeшествие по голубым бухтам",
        nameKey: "excursion4",
        descriptionKey: "excursion4_desc",
        label: "НОВИНКА !!!",
        labelKey: "new",
        images: [
            "/images/excursions/excursion4_1.webp",
            "/images/excursions/excursion4_2.webp",
        ],
        price: 30,
        oldprice: 35,
        category: ["excursion", "from_kemer", "popular"],
    },
    {
        id: 5,
        name: "Голубые бухты на закате + гора Химера",
        nameKey: "excursion5",

        descriptionKey: "excursion5_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion5_1.webp",
            "/images/excursions/excursion5_2.webp",
        ],
        price: 35,
        oldprice: 45,
        category: ["excursion", "from_kemer", "popular"],
    },
    {
        id: 6,
        name: 'Яхта "La Melita" 28m',
        nameKey: "excursion6",
        descriptionKey: "excursion6_desc",
        label: "Уточняйте стоимость по телефону",
        labelKey: "take_price",
        images: [
            "/images/excursions/excursion6_1.webp",
            "/images/excursions/excursion6_2.webp",
        ],
        price: "500",
        oldprice: "",
        category: ["rent_yaht", "excursion", "from_kemer", "popular"],
    },
    {
        id: 7,
        name: "Bmw 218 (автомат)",
        nameKey: "excursion7",
        descriptionKey: "excursion7_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion7_1.webp",
            "/images/excursions/excursion7_2.webp",
        ],
        price: 300,
        oldprice: "",
        category: [
            "rent_avto",
            "excursion",
            "from_kemer",
            "popular",
            "individual",
        ],
    },
    {
        id: 8,
        name: "Рыбалка в Анталии TROLLING & JEEGİNG",
        nameKey: "excursion8",
        descriptionKey: "excursion8_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion8_1.webp",
            "/images/excursions/excursion8_2.webp",
        ],
        price: 1200,
        oldprice: 1250,
        category: [
            "excursion",
            "from_kemer",
            "popular",
            "individual",
            "transfers",
            "medicine",
            "rent_villa",
            "vip",
            "shopping",
        ],
    },
    {
        id: 9,
        name: "Экскурсия в Каш + пляж Капуташ",
        nameKey: "excursion9",
        descriptionKey: "excursion9_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion9_1.webp",
            "/images/excursions/excursion9_2.webp",
        ],
        price: 50,
        oldprice: 60,
        category: [
            "excursion",
            "from_kemer",
            "popular",
            "individual",
            "transfers",
            "medicine",
            "rent_villa",
            "vip",
            "shopping",
        ],
    },
    {
        id: 10,
        name: "Стамбул на 1 день (авиаперелёт)",
        nameKey: "excursion10",
        descriptionKey: "excursion10_desc",
        label: "Скиидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion10_1.webp",
            "/images/excursions/excursion10_2.webp",
        ],
        price: 285,
        oldprice: 295,
        category: [
            "excursion",
            "from_kemer",
            "popular",
            "individual",
            "transfers",
            "medicine",
            "rent_villa",
            "vip",
            "shopping",
        ],
    },
    {
        id: 11,
        name: "Трансфер Аэропорт Анталия Кемер",
        nameKey: "excursion11",
        descriptionKey: "excursion11_desc",
        label: "Заказ трансфера",
        labelKey: "order_transfer",
        images: [
            "/images/excursions/excursion11_1.webp",
            "/images/excursions/excursion11_2.webp",
        ],
        price: 0,
        oldprice: 0,
        category: [
            "excursion",
            "from_kemer",
            "popular",
            "individual",
            "transfers",
            "medicine",
            "rent_villa",
            "vip",
            "shopping",
        ],
    },
];
