export const exscursions = [
    {
        id: 1,
        name: "Остров 'Сулу ада' (Мальдивы Адрасан)",
        nameKey: "exscursion1",
        description:
            "Возможность заказа, не выходя из отеля, сохранит Ваше ценное время. Трансфер организуем из всех регионов Анталии. Работаем БЕЗ ПРЕДОПЛАТ! Оплата - во время тура! Оплатить можно на Сбербанк на Каспи и в USDT",
        descriptionKey: "exscursion1_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion1_1.webp",
            "/images/excursions/excursion1_2.webp",
        ],
        price: 25,
        oldprice: 35,
        category: "excursion",
        popular: true,
        individual: true,
    },
    {
        id: 2,
        name: "Турецкие Мальдивы сулу ада на рассвете",
        nameKey: "exscursion2",
        description:
            "Составим график Вашего отдыха по самому удобному для Вас плану. Подробности экскурсии отправим Вам на WhatsApp, Viber или Telegram",
        descriptionKey: "exscursion2_desc",
        label: "НОВИНКА !!!",
        labelKey: "new",
        images: [
            "/images/excursions/excursion2_1.webp",
            "/images/excursions/excursion2_2.webp",
        ],
        price: 35,
        oldprice: 40,
        category: "excursion",
        popular: true,
        individual: false,
    },
    {
        id: 3,
        name: "Турецкие Мальдивы сулу ада на закате",
        nameKey: "exscursion3",
        description:
            "Составим график Вашего отдыха по самому удобному для Вас плану. Подробности экскурсии отправим Вам на WhatsApp, Viber или Telegram",
        descriptionKey: "exscursion3_desc",
        label: "Скидка",
        labelKey: "discount",
        images: [
            "/images/excursions/excursion3_1.webp",
            "/images/excursions/excursion3_2.webp",
        ],
        price: 30,
        oldprice: 35,
        category: "excursion",
        popular: true,
        individual: false,
    },
    {
        id: 4,
        name: "Путeшествие по голубым бухтам",
        nameKey: "exscursion4",
        description:
            "Составим график Вашего отдыха по самому удобному для Вас плану. Подробности экскурсии отправим Вам на WhatsApp, Viber или Telegram",
        descriptionKey: "exscursion4_desc",
        label: "НОВИНКА !!!",
        labelKey: "new",
        images: [
            "/images/excursions/excursion4_1.webp",
            "/images/excursions/excursion4_2.webp",
        ],
        price: 30,
        oldprice: 35,
        popular: true,
        individual: false,
    },
    {
        id: 5,
        name: "Голубые бухты на закате + гора Химера",
        nameKey: "exscursion5",
        description:
            "Составим график Вашего отдыха по самому удобному для Вас плану. Подробности экскурсии отправим Вам на WhatsApp, Viber или Telegram",
        descriptionKey: "exscursion5_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/excursion5_1.webp",
            "/images/excursions/excursion5_2.webp",
        ],
        price: 35,
        oldprice: 45,
        category: "excursion",
        popular: true,
        individual: true,
    },
    {
        id: 6,
        name: 'Яхта "La Melita" 28m',
        nameKey: "exscursion6",
        description:
            "УТОЧНЯЙТЕ СТЙМОСТЬ НАПИСАВ В ЛИЧКУ! Яхта 'La Melita' в Анталии. Максимум гостей: 12. Длина яхты: 26 m. Ширина яхты: 5 m. Утренний тур: 09:30 - 15:30. Вечерний тур: 16:30 - 20:30. Тип: Моторные яхты.Категория: Дневные туры. Год постройки: 2000. Год обновления: 2023. Модель: SUNSEEKER. Яхта Анталии в аренду для вашего комфортного отдыха! Насладитесь прекрасным обслуживанием и особыми услугами у нас на борту! Маршрут: - Водопад Дюден, - Черепаший остров, - Бухта Малый Чалтыджак. • Кондиционеры, • Питание на борту,• Полотенца, • WiFi, • Телевизор, — Закуски: Сезонные фрукты, Десерт, Креветки,Канапе ассорти, Орехи ассорти, — Горячие закуски: Омары, Раки, Голубой краб, Кальмар, Креветки, Морепродукты. — Обед: Курица филе, Куриный шашлык, Антрекот из говядины или отбивные из баранины, Рыба в соли, Рис, Макароны, Картофель фри, Салат, Турецкие закуски и соусы, Фрукты/десерты/снеки, Безалкогольные напитки, Пиво, Вино(красное, белое,розовое)",
        descriptionKey: "exscursion6_desc",
        label: "Уточняйте стоимость по телефону",
        labelKey: "new",
        images: [
            "/images/excursions/yaht_1_1.webp",
            "/images/excursions/yaht_1_2.webp",
        ],
        price: "500",
        oldprice: "",
        category: "yaht",
        popular: true,
        individual: true,
    },
    {
        id: 7,
        name: "Bmw 218 (автомат)",
        nameKey: "exscursion7",
        description:
            "BMW 218. Коробка передач: Автомат. Топливо: Дизель. Вместимость: 4 человека. Страхование / Каско.Страхование полный КАСКО не действует (на проткнутые колёса и разбитые окна).В случае ДТП: • Обязательно связаться с нашим менеджером, • Не покидать место аварии до прибытия дорожной полиции,Страховка не действует, если: • Водитель во время аварии находился в алкогольном или наркотическом опьянение,• Клиент передал управление автомобилем , лицу без водительских прав или не внесенного в договор с нашей компании о прокате транспорта, • Клиент скрылся с места ДТП. Ограниченный пробег За сутки 150км, Срок аренды: • Минимальный срок проката автомобиля не менее суток (24 часа), • Отсчет времени, начинается с момента оформления, • При превышение оплаченного срока аренды на 59 минут, взимается оплата за полные сутки. Обязательные документы: • Загранпаспорт (возраст не менее 23 года),• Водительское удостоверение (стаж вождения не менее 5 лет). Топливная политика: • Автомобиль необходимо вернуть с тем же количеством топлива, что и при получении, во избежание дополнительной платы за нехватку топлива. • Возврат денег за неиспользованное топливо не предусмотрен.",
        descriptionKey: "exscursion7_desc",
        label: "Новинка",
        labelKey: "new",
        images: [
            "/images/excursions/avto_1_1.webp",
            "/images/excursions/avto_1_2.webp",
        ],
        price: 300,
        oldprice: "",
        category: "avto",
        popular: true,
        individual: true,
    },
];
