export const NavList = [
    { id: 1, name: "About Us", nameKey: "about", titleKey: "aboutTitle" },
    { id: 2, name: "Blog", nameKey: "blog", titleKey: "blogTitle" },
    { id: 3, name: "Contacts", nameKey: "contacts", titleKey: "contactsTitle" },
    { id: 4, name: "Questions", nameKey: "faq", titleKey: "faqTitle" },
    {
        id: 5,
        name: "From Alanya",
        nameKey: "from_alania",
        titleKey: "from_alaniaTitle",
    },
    {
        id: 6,
        name: "From Antalya",
        nameKey: "from_antalia",
        titleKey: "from_antaliaTitle",
    },
    {
        id: 7,
        name: "From Belek",
        nameKey: "from_belek",
        titleKey: "from_belekTitle",
    },
    {
        id: 8,
        name: "From Kemer",
        nameKey: "from_kemer",
        titleKey: "from_kemerTitle",
    },
    {
        id: 9,
        name: "From Marmaris",
        nameKey: "from_marmaris",
        titleKey: "from_marmarisTitle",
    },
    { id: 10, name: "Home", nameKey: "main", titleKey: "mainTitle" },

    { id: 11, name: "more", nameKey: "more", titleKey: "moreTitle" },
    {
        id: 12,
        name: "Car Rental",
        nameKey: "rent_avto",
        titleKey: "rent_avtoTitle",
    },
    {
        id: 13,
        name: "Villa rental",
        nameKey: "rent_villa",
        titleKey: "rent_villaTitle",
    },
    {
        id: 14,
        name: "Yacht Rentals",
        nameKey: "rent_yaht",
        titleKey: "rent_yahtTitle",
    },
    { id: 16, name: "Reviews", nameKey: "reviews", titleKey: "reviewsTitle" },
    {
        id: 15,
        name: "Shopping",
        nameKey: "shopping",
        titleKey: "shoppingTitle",
    },
    {
        id: 16,
        name: "Transfers",
        nameKey: "transfers",
        titleKey: "transfersTitle",
    },
    { id: 17, name: "VIP excursions", nameKey: "vip", titleKey: "vipTitle" },
];
