export const NavList = [
    { id: 1, name: "About Us", nameKey: "about" },
    { id: 2, name: "Blog", nameKey: "blog" },
    { id: 3, name: "Contacts", nameKey: "contacts" },
    { id: 4, name: "Questions", nameKey: "faq" },
    { id: 5, name: "From Alanya", nameKey: "from_alania" },
    { id: 6, name: "From Antalya", nameKey: "from_antalia" },
    { id: 7, name: "From Belek", nameKey: "from_belek" },
    { id: 8, name: "From Kemer", nameKey: "from_kemer" },
    { id: 9, name: "From Marmaris", nameKey: "from_marmaris" },
    { id: 10, name: "Home", nameKey: "main" },
    { id: 11, name: "Medicine", nameKey: "medicine" },
    { id: 12, name: "more", nameKey: " more" },
    { id: 13, name: "Car Rental", nameKey: "rent_avto" },
    { id: 14, name: "Villa rental", nameKey: "rent_valla" },
    { id: 15, name: "Yacht Rentals", nameKey: "rent_yaht" },
    { id: 16, name: "Reviews", nameKey: "rewiews" },
    { id: 17, name: "Shopping", nameKey: "shopping" },
    { id: 17, name: "Transfers", nameKey: "transfers" },
    { id: 17, name: "VIP excursions", nameKey: "vip" },
];
