export const ServicesList = [
    {
        id: 1,
        name: "Экскурсии",
        nameKey: "service1",
        link: "/catalog/category/from_kemer",
        img: "/images/services/tour.webp",
    },
    {
        id: 2,
        name: "Аренда яхты",
        nameKey: "service2",
        link: "/catalog/category/rent_yaht",
        img: "/images/services/boat.webp",
    },
    {
        id: 3,
        name: "Аренда авто",
        nameKey: "service3",
        link: "/catalog/category/rent_avto",
        img: "/images/services/auto.webp",
    },
    {
        id: 4,
        name: "Трансфер",
        nameKey: "service4",
        link: "/catalog/category/transfers",
        img: "/images/services/transfer.webp",
    },
    {
        id: 5,
        name: "VIP экскурсии",
        nameKey: "service5",
        link: "/catalog/category/vip",
        img: "/images/services/vipTour.webp",
    },
    {
        id: 6,
        name: "Шоппинг",
        nameKey: "service6",
        link: "/catalog/category/shopping",
        img: "/images/services/shopping.webp",
    },
    {
        id: 7,
        name: "Недвижимость",
        nameKey: "service7",
        link: "/catalog/category/rent_villa",
        img: "/images/services/rent.webp",
    },
    {
        id: 8,
        name: "Медицина",
        nameKey: "service8",
        link: "/catalog/category/medicine",
        img: "/images/services/medicine.webp",
    },
    {
        id: 9,
        name: "Вопросы",
        nameKey: "service9",
        link: "/catalog/category/faq",
        img: "/images/services/faq.webp",
    },
    {
        id: 10,
        name: "О нас",
        nameKey: "service10",
        link: "/catalog/category/about",
        img: "/images/services/about.webp",
    },
    {
        id: 11,
        name: "Контакты",
        nameKey: "service11",
        link: "/catalog/category/contacts",
        img: "/images/services/contacts.webp",
    },
    {
        id: 12,
        name: "Отзывы",
        nameKey: "service12",
        link: "/catalog/category/reviews",
        img: "/images/services/review.webp",
    },
];
